### Variables
@baseUrl = http://localhost:3000
@authToken = YOUR_AUTH_TOKEN  # Replace with a valid token if needed

### Users Routes

### GET Users
GET {{baseUrl}}/users HTTP/1.1

### POST Users
POST {{baseUrl}}/users HTTP/1.1
Content-Type: application/json

{
   "name": "John Doe",
   "email": "john.doe2@example.com",
   "password": "password123"
}

### GET User by ID
GET {{baseUrl}}/users/USER_ID HTTP/1.1

### PATCH Update User
PATCH {{baseUrl}}/users/USER_ID HTTP/1.1
Content-Type: application/json

{
   "name": "Updated Name"
}

### DELETE User
DELETE {{baseUrl}}/users/USER_ID HTTP/1.1

### Products Routes

### GET Products
GET {{baseUrl}}/products HTTP/1.1

### POST Products
POST {{baseUrl}}/products HTTP/1.1
Content-Type: application/json

{
   "name": "Product Name",
   "description": "Product Description",
   "price": 200.0,
   "images": ["https://picsum.photos/200", "https://picsum.photos/200"] ,
   "stock": 10
}

### GET Product by ID
GET {{baseUrl}}/products/674e3d556cff29ac806a6f67 HTTP/1.1

### PATCH Update Product
PATCH {{baseUrl}}/products/674e3d556cff29ac806a6f67 HTTP/1.1
Content-Type: application/json

{
   "name": "Updated Product Name",
   "price": 250.0
}

### DELETE Product
DELETE {{baseUrl}}/products/674e3c3937c3d3cdf17bfabc HTTP/1.1

### Orders Routes

### GET Orders
GET {{baseUrl}}/orders HTTP/1.1

### POST Orders
POST {{baseUrl}}/orders HTTP/1.1
Content-Type: application/json

{
   "userId": "USER_ID",
   "productIds": ["PRODUCT_ID_1", "PRODUCT_ID_2"],
   "totalPrice": 200.0
}
