version: '3.8'

networks:
  app-network:  # Define a custom network
    driver: bridge
services:
  backend:
    container_name: backend
    build:
      context: ./online-store-backend/
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: mongodb://mongo:27017/online-store
      AUTH_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZWFiN2E0NmM5NmNkY2JlNzA0MGI2OTM5YjE4YmM1YWYzMGJiYmVmZGU3ZmNlZTg0OGQ3NDU1YTY4ZmQ0NWE1NzJmNTZkNTAwYTA3MzhiM2UiLCJpYXQiOjE3MzM4NjgxMDguNTQzODkxLCJuYmYiOjE3MzM4NjgxMDguNTQzODkyLCJleHAiOjE3NjU0MDQxMDguNTI0NzQzLCJzdWIiOiI5ZGIxYmE4Yy03ZDEzLTQzZDItYjYzNi1iNjNlYmY0ZTYxOTEiLCJzY29wZXMiOlsiY2FydC1yZWFkIiwiY2FydC13cml0ZSIsImNvbXBhbmllcy1yZWFkIiwiY29tcGFuaWVzLXdyaXRlIiwiY291cG9ucy1yZWFkIiwiY291cG9ucy13cml0ZSIsIm5vdGlmaWNhdGlvbnMtcmVhZCIsIm9yZGVycy1yZWFkIiwicHJvZHVjdHMtcmVhZCIsInByb2R1Y3RzLWRlc3Ryb3kiLCJwcm9kdWN0cy13cml0ZSIsInB1cmNoYXNlcy1yZWFkIiwic2hpcHBpbmctY2FsY3VsYXRlIiwic2hpcHBpbmctY2FuY2VsIiwic2hpcHBpbmctY2hlY2tvdXQiLCJzaGlwcGluZy1jb21wYW5pZXMiLCJzaGlwcGluZy1nZW5lcmF0ZSIsInNoaXBwaW5nLXByZXZpZXciLCJzaGlwcGluZy1wcmludCIsInNoaXBwaW5nLXNoYXJlIiwic2hpcHBpbmctdHJhY2tpbmciLCJlY29tbWVyY2Utc2hpcHBpbmciLCJ0cmFuc2FjdGlvbnMtcmVhZCIsInVzZXJzLXJlYWQiLCJ1c2Vycy13cml0ZSIsIndlYmhvb2tzLXJlYWQiLCJ3ZWJob29rcy13cml0ZSIsIndlYmhvb2tzLWRlbGV0ZSIsInRkZWFsZXItd2ViaG9vayJdfQ.x-lng4BKnFvPX0zNboHDPBGGhdwP4e0nko5Le13gdUbsPRbF1ZZnqXia3b6y-Hybp3__VK3fWLy_ZGhkWmaa_NVyIs19XPgJXbPZ0WwNCjL3ZZxLV2EQWwLP9qvIyLCUQTxoHLVQmszvWFancYrxOdH8pYB-LpDxealW-FlB2YC6jXPngeENCDho42j6KpwKfVxrU2WRs8exsq9BWg0dpaO1ZK9uWETHaCjQjlFsjTvGBS3i25oZILCI24vsbWN98XmUP4Ym20ohYL9bJ_84T2_83ICNRazct24bNg5w2BtbFiH8lEYC68-JqwHe95O5evD9VPkWrOCXGC3eMUfz1MDkOvxDaIXKdSolkrLyAGiXK8E-L77u252Ok-Gg3I1PLOLnPXZqYodGQ1eO9MojxSkAooRK_dWzZv9plJlDk8iJwkFwaQYtszVqijRFhHMrFH3XrS4oJLNLdgPsKsZ8bOzJlS65nKeGfp1RCnd7NyLPxl4ueupMu5TpVc825vRzd0Of6ra0KMuxl8wqDbU0JUSa6vNSTpySP122LXfkhjIAuT1m4APH-wDW-Io-WPsiEPWu7diMBEg_kAD_E036hcLZUU3OuXVASXJl5G0wqu3flnB4iVY3QPrG6zxL7pJedKLFyVBzTGPTle30rho40nz62ZiZIfdxk3wkbw2JRB4
    depends_on:
      - mongo
    networks:
      - app-network  # Attach to the custom network
    volumes:
      - ./online-store-backend:/home
      - node_modules:/home/node_modules
  front-end:
    container_name: frontend
    build:
      context: ./online-store-frontend/
      
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    networks:
      - app-network  # Attach to the custom network
    volumes:
      - ./online-store-frontend:/home
      - node_modules_frontend:/home/node_modules

  mongo:
    container_name: mongodb
    image: mongo:6.0
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network  # Attach to the custom network
volumes:
  mongo-data:
  node_modules:
  node_modules_frontend: